trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    echo "No build step defined" 
  displayName: 'Placeholder for build step'

- script: |
    echo "No tests defined"
  displayName: 'Placeholder for test step'
